// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for FlowTimeUpdaterFunction
 */
export interface FlowTimeUpdaterFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/core/flows/flow-time-updater/flow-time-updater.
 */
export class FlowTimeUpdaterFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: FlowTimeUpdaterFunctionProps) {
    super(scope, id, {
      description: 'src/core/flows/flow-time-updater/flow-time-updater.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/core/flows/flow-time-updater/flow-time-updater.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}